### ISSUE TITLE
Add listener for Pipeline plugin events

### ISSUE THREAD

**Issue by Jimilian** [jenkinsci/groovy-events-listener-plugin#20]
For more information look into:
https://groups.google.com/forum/#!topic/jenkinsci-dev/PzLjXrm7S2g

@nickgrealy, what do you think?

**Comment by nickgrealy** [comment]
I'm not quite across what events are available for the [Pipeline plugin](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin), but if others are trying to tap into them, then I don't see why we can't/shouldn't as well. Have you used/Are you using the plugin?

I assume we just want to have our own copy of [PipelineEventListener.java](https://github.com/jenkinsci/blueocean-plugin/blob/feature/JENKINS-36211/blueocean-events/src/main/java/io/jenkins/blueocean/events/PipelineEventListener.java), correct?

[PipelineEventChannel.Event](https://github.com/jenkinsci/blueocean-plugin/blob/feature/JENKINS-36211/blueocean-events/src/main/java/io/jenkins/blueocean/events/PipelineEventChannel.java)
- pipeline_start
- pipeline_block_start
- pipeline_step
- pipeline_block_end
- pipeline_end

**Comment by Jimilian** [comment]
@nickgrealy, yes, we are using pipeline plugin in some projects. And yes, I will be able to find some time to do it.

**Comment by nickgrealy** [comment]
@Jimilian -> Admin 👍

**Comment by webratz** [comment]
has that ever been implemented?
