### ISSUE TITLE
Scheduler Doesn't Seem to Work

### ISSUE THREAD

**Issue by sterrana11** [jenkinsci/groovy-events-listener-plugin#27]
### Steps to reproduce
How can we reproduce the issue
1. enter "1" into the scheduler field 

### Expected behaviour
Groovy script should be executed every minute

### Actual behaviour
Groovy script never executed because of timer 

### Server configuration

**Operating system**: OSX

**Jenkins Version**: 2.7.1

**Plugin Version**: 1.014

**Comment by Jimilian** [comment]
Yes, unfortunately, it was broken in 1.014. You can use 1.013 if you don't need `queue` and `node` events. I will try to fix it on this week.

**Comment by afeblot** [comment]
Hi,
I will have to deploy your plugin on around 10 jenkins, and I'd need the scheduler event. Do you plan to release a new official version soon including this fix, or shall I rather compile it myself and manually upload it?

Thanks

**Comment by Jimilian** [comment]
@afeblot, unfortunately, right now new releases are blocked. @nickgrealy, maybe you can create new release without https://github.com/jenkinsci/groovy-events-listener-plugin/blob/master/build.gradle#L82 ?
