### ISSUE TITLE
enhancement: configurable test event

### ISSUE THREAD

**Issue by vredda** [jenkinsci/groovy-events-listener-plugin#32]
Thank you guys for this cool plugin that let me not to write my own one!  ;)

A tiny enhancement request: configurable test event instead of just 'RunListener.onStarted'

**Comment by Jimilian** [comment]
Yes, I agree that @nickgrealy did a great job :)
Can you, please, explain why do you need this feature? Which User Scenario needs it?

p.s. I now that this feature can be implemented quite easy, but, unfortunately, current state of master blocks new releases (it breaks some feature that are really useful, i.e. ability to import any class from any plugin").

**Comment by vredda** [comment]
I mean a line edit by the 'Test Groovy Code' button in plugin configuration section.
It's content ('RunListener.onStarted' by default) goes to 'event' variable for running 'Groovy Code'.
The scenario is testing: now I have to additionally handle 'RunListener.onStarted' event in my script when in fact it is supposed to only handle 'GlobalEventsPlugin.start'. 
And things might get hairier when there will be a need to handle job start also, or handle 2+ events in different ways.

**Comment by Jimilian** [comment]
I see. I think this button should fire `GlobalEventsPlugin.start`
