### ISSUE TITLE
Plugin can't install due to groovy version

### ISSUE THREAD

**Issue by louisdj** [jenkinsci/groovy-events-listener-plugin#33]
### Steps to reproduce
How can we reproduce the issue
1. Setup jenkins docker version
2. Install the plugin

### Expected behaviour
The plugin should be installed

### Actual behaviour
The plugin does not install. We receive an error about the Groovy version:

> groovy-all is loaded in version 2.4.4 and you are trying to load version 2.4.7

### Server configuration

**Operating system**: Docker

**Jenkins Version**: latest

**Plugin Version**: latest

**Comment by FloriansGit** [comment]
I had the same problem at for me it looks like a conflict between the Groovy version coming with Jenkins itself (2.4.4) and the Groovy version installed/linked in the Groovy Plugin https://plugins.jenkins.io/groovy

It worked when I removed all "Groovy installation" Groovy plugin configuration settings.
