### ISSUE TITLE
Only execute script for registered events (to mitigate performance impacts)

### ISSUE THREAD

**Issue by nickgrealy** [jenkinsci/groovy-events-listener-plugin#6]

**Comment by Jimilian** [comment]
Do you have a plan how to implement this? I was thinking about checkboxes in plugin settings.

**Comment by nickgrealy** [comment]
No, I didn't have a plan... I liked the simplicity of the current plugin, so didn't want to muddy the UI too much. Checkboxes sound good... what were you thinking, something like this?
http://jsbin.com/wamito/edit?html,output

Btw, I've made you a collaborator on the project! So you should be able to just push your changes whenever you want.

**Comment by Jimilian** [comment]
Yes, second version looks good!

**Comment by Jimilian** [comment]
Done in https://github.com/jenkinsci/groovy-events-listener-plugin/pull/13.
