### ISSUE TITLE
Unable to manage JOB_DELETE event

### ISSUE THREAD

**Issue by fgiacomelli** [jenkinsci/groovy-events-listener-plugin#64]
### Steps to reproduce
How can we reproduce the issue
1. Configure plugin to handle the job delete event (I need to manage this event: if (event == Event.JOB_DELETED)
2. Log all events received by plugin simply with:
![image](https://user-images.githubusercontent.com/6031305/81308231-d495f600-9081-11ea-86ae-6e339ab058e4.png)
3. Delete a Job (tested from both job dashboard or deleting the job inside its configuration page)
4. Open Log page 

### Expected behaviour
I should see that some event is logged when the job is deleted

### Actual behaviour
In the log I can only see events related to build completion or finalization (I just schedule a build and immediately forced to stop it), but no log for deletion event

Event: RunListener.onCompleted
May 07, 2020 4:40:18 PM INFO org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
Workspace: C:\Jenkins\workspace\test_del
May 07, 2020 4:40:18 PM INFO org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
Event: RunListener.onFinalized
May 07, 2020 4:40:18 PM INFO org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
Workspace: C:\Jenkins\workspace\test_del

### Server configuration

**Operating system**:
Windows 10 ver 1909

**Jenkins Version**:
2.222.3

**Plugin Version**:
1.014

**Comment by fgiacomelli** [comment]
some news?

**Comment by markyjackson-taulia** [comment]
I tried reproducing this and could not.
