### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by davegallant** [jenkinsci/groovy-events-listener-plugin#65]
The latest release of this plugin is not loadable due to this issue:
https://github.com/jenkinsci/groovy-events-listener-plugin/issues/48

The fix has made it into master:
https://github.com/jenkinsci/groovy-events-listener-plugin/pull/61

### Expected behaviour
The latest version should be published to https://plugins.jenkins.io/groovy-events-listener-plugin/#releases and install without issues.

### Actual behaviour
The latest release is `1.017` and does not contain the fix in https://github.com/jenkinsci/groovy-events-listener-plugin/pull/61 preventing this plugin from being loaded successfully.

### Server configuration

**Operating system**:
Amazon Linux 2

**Jenkins Version**:
Jenkins LTS 2.249.3

**Plugin Version**:
1.017

**Comment by murthysrd** [comment]
Is someone working on publishing `1.019` with this fix ?

**Comment by raymondwu1** [comment]
New release [1.019](https://github.com/jenkinsci/groovy-events-listener-plugin/releases/tag/1.019) has been published
