### ISSUE TITLE
Add ExecutorListener to handle task execute event

### ISSUE THREAD

**Issue by lpb1** [jenkinsci/groovy-events-listener-plugin#95]
### What feature do you want to see added?

The plugin can use QueueListener handle Item(Task)'s Queue Event, but it can not get Task's execute status.
ExecutorListener in hudson.model package can help us to handle Task Execution Events.
doc: https://javadoc.jenkins.io/hudson/model/ExecutorListener.html

### Are you interested in contributing this feature?

I have already added and tested this feature locally, how can I create a pull request to the repo?

**Comment by raymondwu1** [comment]
Hi @lpb1, please see the [contributing guidlines](https://github.com/jenkinsci/groovy-events-listener-plugin/blob/main/.github/CONTRIBUTING.md) for how to create a PR for this repo.
